[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
test_speed = 115200
monitor_filters = esp32_exception_decoder, time

; Force C++20 standards
build_unflags = -std=gnu++11
build_flags = 
    -std=gnu++2a

; micro-ROS Configuration
board_microros_transport = serial
board_microros_distro = humble 

lib_deps =
    https://github.com/micro-ROS/micro_ros_platformio
    ; Your local lib is already included through the folder structure, 
    ; but explicitly adding it doesn't hurt if you want to externalize it:
    ; StatusLed